version: '3'

networks:
  url-shortener:
    driver: bridge

services:
  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BASE_URL=http://localhost:8080
    networks:
      - url-shortener
    volumes:
      - ./backend-api:/app
  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
      # - .:/app
      # - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - WATCHPACK_POLLING=true
    networks:
      - url-shortener
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    networks:
      - url-shortener
